version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      # dockerfile: Dockerfile
    container_name: book-catalog-service
    environment:
      - DATABASE_URL= postgresql://sit722p722part3_user:BJY6qPUUQkP7xqxGC6Nz5xj25s2RywRd@dpg-crq03kggph6c73a4q790-a.oregon-postgres.render.com/sit722p722part3
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - microservices_network

  inventory_management:
    build:
      context: ./inventory_management
      # dockerfile: Dockerfile
    container_name: inventory-management-service
    environment:
      - DATABASE_URL= postgresql://sit722p722part3_user:BJY6qPUUQkP7xqxGC6Nz5xj25s2RywRd@dpg-crq03kggph6c73a4q790-a.oregon-postgres.render.com/sit722p722part3
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - microservices_network
    
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: sit722p722part3_user
      POSTGRES_PASSWORD: BJY6qPUUQkP7xqxGC6Nz5xj25s2RywRd
      POSTGRES_DB: sit722p722part3
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/;ib/postgresql/data
    networks:
      - microservices_network
  
networks:
  microservices_network:
    driver: bridge
    
volumes:
  postgres_data:



